// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

struct BoidData
{
    float2 velocity;
    float2 position;
};

#define THREAD_GROUP_SIZE 64

// Buffers
RWTexture2D<float4> output;
RWStructuredBuffer<BoidData> boids_data_buffer;     // Boids Data read-write structured buffer

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    output[id.xy] = float4(id.x & id.y, (id.x & 15)/15.0, (id.y & 15)/15.0, 0.0);
}
